version: "2"
services:
  mongo1:
    image: mongo
    container_name: mongo1
    hostname: mongo1
    ports:
      - "27017:27017"
    volumes:
      - $HOME/workspace/mongodb-docker-rs/data/db1:/data/db
    command: --storageEngine wiredTiger --smallfiles --oplogSize 128 --replSet repTest --dbpath /data/db
  mongo2:
    image: mongo
    container_name: mongo2
    hostname: mongo2
    ports:
      - "27018:27017"
    volumes:
      - $HOME/workspace/mongodb-docker-rs/data/db2:/data/db
    command: --storageEngine wiredTiger --smallfiles --oplogSize 128 --replSet repTest --dbpath /data/db
  mongo3:
    image: mongo
    container_name: mongo3
    hostname: mongo3
    ports:
      - "27019:27017"
    volumes:
      - $HOME/workspace/mongodb-docker-rs/data/db3:/data/db
    command: --storageEngine wiredTiger --smallfiles --oplogSize 128 --replSet repTest --dbpath /data/db